---
title: js笔记10
date: 2020-04-03 09:18:53
tags:
    -js
    -学习笔记
categories: 前端
---
## Promise

pending 准备阶段
resolved 成功状态
rejected 拒绝状态
.then函数有两个参数一个是成功状态的函数一个是拒绝状态
resolve和reject改变状态

```(javascript)
new promise((resolve,reject)=>{
resolve("改为成功状态")；
//reject("改为拒绝状态")
    }).then(value=>{
console.log("成功的执行函数")
},reason=>{
    console.log("拒绝后的执行函数")
})
```

promise对象也是同步任务他的then方法会放在微任务中
只有promise中通知有任务才会将then放在微任务，比如resolve改变状态通知
```(javascript)
执行顺序同步任务微任务(promise.then)宏任务
setTimeout(()=>{
    console.log("宏任务1")
},0)
new Promise(resolve=>{
    resolve();
    console.log("同步任务1");

}).then(value=>{
    console.log("成功，微任务1");
})
console.log("同步任务2")
//结果是同步任务1同步任务2微任务1宏任务1    
```

下面的就是宏任务比微任务提前的例子
```(javascript)
new Promise(resolve=>{
    setTimeout(()=>{    //宏任务开始执行的时候才传递成功状态使得微任务创建成功，在没有执行resolve之前微任务不创建
    console.log("宏任务1")
    resolve();
},0)
    console.log("同步任务1");

}).then(value=>{
    console.log("成功，微任务1");
})
console.log("同步任务2")
```

resolve(value)  成功时会将value传递给then里面的第一个函数
下例中p2 返回了p1 所以此时p2的状态已经无意义了，后面的then是对p1状态的处理。
当promise做为参数传递时，需要等待promise执行完才可以继承，下面的p2需要等待p1执行完成。

因为p2 的resolve 返回了 p1 的promise，所以此时p2 的then 方法已经是p1 的了
正因为以上原因 then 的第一个函数输出了 p1 的 resolve 的参数
```(javascript)
const p1 = new Promise((resolve, reject) => {
  // resolve("fulfilled");
  reject("rejected");
});
const p2 = new Promise(resolve => {
  resolve(p1);
}).then(
  value => {
    console.log(value);
  },
  reason => {
    console.log(reason);
  }
);
```

状态单项不可逆
一旦有了resolve后面有reject也不执行
then 默认情况下也反映的是promise状态为成功
```
then(function(value){
  //value是resolve()里面传的参数
},function(reason){
  //reason是reject里面传得参数
})
```

如果只关心失败时状态，then 的第一个参数传递 null
promise 传向then的传递值，如果then没有可处理函数，会一直向后传递
then后面的then接收的值是上一个的返回值,then返回的是promise，默认是已解决
then里面的函数返回的是promise的话那么then后面的then就处理的是返回的promise
```(javascript)
then(value=>{
    return {     //系统会封装成promise，只要返回的对象理由then方法，或者返回一个类中有静态方法
        then(resolve,reject){
            resolve("")
        }
    }
})
```

reject可以抛一个错误对象
```(javascript)
new Promise((resolve,reject)=>{
    reject(new Error("错误"))
}).then(null,reason=>{console.log(reason.message)})  //.message可以查看错误对象的信息
```

或者promise直接抛一个错误
```(javascript)
new Promise((resolve,reject)=>{
    throw new Error("fail")   //会直接抛给then的错误处理函数
}).then(null,reason=>{console.log(reason.message)})
```

或者如果在promise中又一个错误也会直接传递给错误处理函数，因为内部有一个try catch机制
```(javascript)
new Promise((resolve,reject)=>{
try{
    hd+1;
}catch(error){
    reject(error)
}
})
```

有一个promise就要有一个then里面的函数去解决状态如果没有就会报错可以用最后面.catch(error=>{})来解决统一的错误
```(javascript)
Promise.reject()和Promise.resolve() 静态方法可直接调用，返回promise需要then解决状态
.finally(()=>{
    console.log("永远会执行不管是否成功")
})
```

Promise.resolve缓存后台数据
```(javascript)
function query(name) {
  const cache = query.cache || (query.cache = new Map());
  if (cache.has(name)) {
    console.log("走缓存了");
    return Promise.resolve(cache.get(name));
  }
  return ajax(`http://localhost:8888/php/user.php?name=${name}`).then(   //ajax里面定义了返回一个promise
    response => {
      cache.set(name, response);
      console.log("没走缓存");
      return response;
    }
  );
}
query("向军").then(response => {
  console.log(response);
});
setTimeout(() => {
  query("向军").then(response => {
    console.log(response);
  });
}, 1000);
```

Promise.resolve也可以直接把带有then方法的对象封装成promise
```(javascript)
let hd = {
    then(resolve,reject){
        resolve("后盾人")
    }
};
Promise.resolve(hd).then(calue=>{
    console.log(value);
})
```

Promise.reject借口和resolve借口类似但.catch()也能接到Promise.reject()
Promise.all([promise1,promise2])  //同时发送两个promise都得解决了才行,否则报错
Promise.all([promise1,promise2]) .then(result=>{console.log(result)}  //返回一个数组。
Promise.allSettled([p1,p2])  //可以接受有拒绝的状态
```(javascript)
let promise1 = new Promise((resolve,reject)=>{
          resolve("jiejue1")
      });
      let promise2 = new Promise((resolve,reject)=>{
          reject("jiejue2")
      });
      Promise.allSettled([promise1,promise2]).then(reasult=>{
        console.log(reasult)            //返回对象数组能获取每个的状态和value或者reason 
      })
```

Promise.race([p1,p2])   //谁快就返回谁
获取用户资料，如果两秒内没有结果 promise.race 状态失败，执行catch 方法
```(javascript)
const api = "http://localhost:8888/php";
const promises = [
  ajax(`${api}/user.php?name=向军`),     //请求时间超过两秒那么就返回下面的promise通过catch能获取错误
  new Promise((a, b) =>
    setTimeout(() => b(new Error("request fail")), 2000)  
  )
];
Promise.race(promises)
.then(response => {
  console.log(response);
})
.catch(error => {
  console.log(error);
});
```
<!-- more -->

map实现队列
```(javascript)
function query(num){
    let promise = Promise.resolve();
    num.map(v=>{
        promise = promise.then(()=>{
            return new Promise(resolve=>{
                setTimeout(()=>{
                    console.log(v);
                    resolve();
                },1000)
            })
        })
    })
}
query([1,2,3,4,5])
```
 
使用reduce封装队列
```(javascript)
function queue(num){
    num.reduce((promise,n)=>{
        return promise.then(()=>{
            return new Promise(resolve=>{
                setTimeout(()=>{
                console.log(n);
                resolve();
                },1000)
            })
        })
    },Promise.resolve())
}
queue([1,2,3,4,5])
```

语法糖
```(javascript)
async function hd(){  //hd()默认返回一个promise默认是解决的
    return ...       //返回的东西可以被then方法接到，可以写一个返回的promise同样可以被then接到
}
```

await是then的语法糖 放在asyns定义的内部函数里才能使用
使用 await 关键词后会等待promise 完

await 后面一般是promise，如果不是直接返回
await 必须放在 async 定义的函数中使用
await 用于替代 then 使编码更优雅
```(javascript)
async function hd(){

    let name = await new Promise(resolve=>{
        resolve("完成")
    })
    console.log(name)   //完成
}
hd()
```

下面是使用async 设置定时器，并间隔时间来输出内容
```(javascript)
async function sleep(ms = 2000) {
  return new Promise(resolve => {
    setTimeout(resolve, ms);
  });
}
async function run() {
  for (const value of ["后盾人", "向军"]) {
    await sleep();
    console.log(value);
  }
}
run();

```

进度条制作
```(javascript)
(async()=>{
    let user = ["后盾人","张三"];
    for(let i = 0; i<user.length;i++){
        let user = await query(user[i])   //query是封装的一个请求后台数据的函数返回的是一个promise
        let progress = ((i+1)/user.length)*100;
        loading.style.width = progress+"%";
        loading.innerHTML = Math.round(progress) + "%";
    }
})()
```

class 和 await的搭配
```(javascript)
class User {
  constructor(name) {
    this.name = name;
  }
  then(resolve, reject) {
    let user = ajax(`http://localhost:8888/php/user.php?name=${this.name}`);
    resolve(user);
  }
}
async function get() {
  let user = await new User("向军");
  console.log(user);
}
get();
```

```(javascript)
class User(){
    get(name){
        let user = ajax(`http://localhost:8888/php/user.php?name=${name}`);
        user.name+="-houdunren"  //本意想在请求过来的名字上加后缀但是不能完成因为这行语句是同步任务而ajax是异步所以并不能达到，异步任务在同步后面
        return user
    }
}
修正
class User(){
    async get(name){
        let user = await ajax(`http://localhost:8888/php/user.php?name=${name}`);
        user.name+="-houdunren" 
        return user
    }
}
```

async和await有多种声明用法，记住只要await在async声明的函数内部就行

async和await错误处理
async声明的函数返回了拒绝的或者错误的promise那么可以用.catch()接到
await错误处理，可以在async中用try catch 抱住await来防止抛出错位，
并行1.Promise.all([p1,p2])
2.
```(javascript)
async function hd() {
  let h1 = p1();
  let h2 = p2();
  await h1;
  await h2;
}
hd();
```